### ISSUE TITLE
The application is not displaying any confirmation message when the “Contact Us” email is being sent.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-artshowcase#12]
Description:  
When the user uses the “Contact Us” form and send a message it does not have any confirmation the the email has being sent correct.

-Env:
Crafter Exigo Blueprint
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Exigo site.
2. Go to the “Contact Us” section.
3. Fill out all the “Contact Us” with valid information.
4. Click on the “Send Message Button”

CURRENT RESULT: 
==================== 
The application is not displaying any confirmation message that the email has being sent correctly.
 
EXPECTED RESULT: 
==================== 
The application should display a message that the email has being sent correctly.

**Comment by efaj** [comment]
We'll use a button like this https://codepen.io/governorfancypants/pen/penmj to give the user feedback

**Comment by efaj** [comment]
Add a timeout that, after 2 seconds, reverts the button to normal state (whether it was in error or success state)

**Comment by efaj** [comment]
assign @juacamar

**Comment by juacamar** [comment]
Bug verified and closed as fixed.
