### ISSUE TITLE
The background videos are not displayed in some browsers.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-artshowcase#14]
Description:
When the user uses the Safari browser the background videos are not displayed.

-Env:
Crafter Exigo Blueprint
Device: MacBook Pro 
Safari Version 8.0.5 (10600.5.17)

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Exigo site.
2. Go to the “Intro” or “Testimonials” section.
3. Review the sections.

CURRENT RESULT: 
==================== 
The application is not displaying the background video of the sections.
 
EXPECTED RESULT: 
==================== 
The application should display the background video of the sections.

**Comment by efaj** [comment]
@kmarcos also experienced this issue. It seems to be related to tomcat/server configuration, it's likely beyond the scope of a blueprint, but it's still being investigated

**Comment by efaj** [comment]
assign @juacamar

**Comment by juacamar** [comment]
Bug reproduced in Apple devices:

Iphone 6 IOS 10.2
Iphone 7 IOS 10.3
Using:
Google Chrome 55.0.2883.79
Firefox 7.5(3349)
Safari

**Comment by efaj** [comment]
Additional information:
Video is loaded and the still is rendered properly.
It seems to be an issue with autoplay, it would seem those mobile devices do not respect the html autoplay attribute.

possible fix: with javascript start the video on doc ready

**Comment by efaj** [comment]
fixed in 1fd5fa553d7463774934d5a7b877403675dde408
and merged in d912272eb88b2b547ce57cb0ca9e355e3a11a4f4

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build 5927e93.
