### ISSUE TITLE
The bullet navigation bar is not working properly in mobile.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-artshowcase#16]
Description:  
The bullet navigation bar is not working properly in mobile.
 
-Env:
Crafter Exigo Blueprint
Device: Android 7.1.1 
 
Google Chrome 58.0.3029.83
 Firefox 53.0.2

REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Exigo site in mobile.
2. Click and review the bullet navigation bar.
 
 
CURRENT RESULT: 
==================== 
The bullet navigation bar is not working properly, a white box is displayed, and in other browsers the bullet navigation bar is not displayed at all.
https://www.screencast.com/t/dw1dRfeyV
 
EXPECTED RESULT: 
==================== 
The bullet navigation bar should be working properly redirecting to the section selected.

**Comment by efaj** [comment]
It was decided to remove the nav bar

58950eac0b2e59ebf9291bb1dfa6e2a4c605f8b6 Removes the nav bar

**Comment by juacamar** [comment]
Bullet nav bar removed, bug verified and closed as fixed
