### ISSUE TITLE
The “Contact Us” section does not perform a correct behavior in Internet Explorer 11.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-artshowcase#18]
Description:  
When the user send a message in the “The “Contact Us” section  in Internet Explorer 11 it does not perform a correct behavior.
 
-Env:
Crafter Exigo Blueprint
Internet Explorer 11.321.14393.0
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Exigo site.
2. Go to the “Contact Us” section.
3. Fill out all the fields
4. Click on the “Send Message” Button
 
 
CURRENT RESULT: 
==================== 
After the user clicks on the “Send Button” it disappears for a couple of seconds instead of displaying a check that proves the email has been sent correctly. Also the fields are not being cleaned.
https://www.screencast.com/t/yTQ3M1ndUVc  
 
EXPECTED RESULT: 
==================== 
After the user clicks on the “Send Button” it should displays a check message hat proves the email has been sent correctly for a couple of seconds and then change to the “Send Message” button again. Also all the fields should be cleaned.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug closed as fixed in build cffd527
