### ISSUE TITLE
The application is displaying an error when all the curators are deleted.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-artshowcase#2]
Description: When the user deletes all the curators are deleted or there are not curators the application displays an error message.

-Env:
Using the Exigo Blueprint
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 

Description: When the user deletes all the curators are deleted or there are not curators the application displays an error message.

PRECONDITIONS: 
==================== 

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with a Exigo bluesite.
2. On the site bar, locate the components section.
3. Click on the edit button of the Curators list.
4. Delete all the curators
4. Click on the Save and Close Button.
5. Go to the Page preview the Curators section.

CURRENT RESULT: 
==================== 
The application displays an error message when all the curators are deleted.
https://www.screencast.com/t/oFGSbu47C9

EXPECTED RESULT: 
==================== 
The application should not display any error message when there are no curators.

**Comment by efaj** [comment]
Fixed in 34f84e00faef331576c492e84ed34e3bfe3167fd

**Comment by juacamar** [comment]
Bug verified and closed as fixed in 34f84e0
