### ISSUE TITLE
The email format validation message is not displayed properly.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-artshowcase#21]
Description:  
The email format validation message is not displayed properly.
 
-Env:
Crafter Exigo Blueprint
Device: MacBook Pro 
Google Chrome Version 58.0.3029.110 (64-bit)
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Exigo site.
2. Go to the “Contact us” section.
3. Fill Out the fields with the next text.
	Your name: Juan	
	Phone: 123456			
	Your Email Address: juan.com
	You Message: Test
4. Click on the “Send Message” button 
 
 
CURRENT RESULT: 
==================== 
The email format validation message is not displayed properly.
https://www.screencast.com/t/PKnbnwNkn 
 
EXPECTED RESULT: 
==================== 
The email format validation message should be displayed properly.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build 8380508.
