### ISSUE TITLE
The application is redirecting to a non existing site, when the “Contact Us” fields are not filled out with values or are filled out with values with wrong format, in Safari browser.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-artshowcase#22]
Description:  
The application is redirecting to a non existing site, when the “Contact Us” fields are not filled out with values or are filled out with values with wrong format  in Safari browser, for mobile and Mac.
 
-Env:
Crafter Exigo Blueprint
 
Device: MacBook Pro 
Safari Version 8.0.5 (10600.5.17)
 
Device: Iphone 6
Google Chrome 55.0.2883.79
Safari IOS 10.2
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Exigo site.
2. Go to the “Contact us” section.
3. Fill Out the fields with the next text.
	Your name: empty	
	Phone: empty		
	Your Email Address: juan.com
	You Message: Test
4. Click on the “Send Message” button 
 
 
CURRENT RESULT: 
==================== 
The application is redirecting to a non existing site.
https://www.screencast.com/t/0CGcJTLU
 
EXPECTED RESULT: 
==================== 
The application should validate the format of the fields and that all field are filled out with pop up messages and the application should not redirect to a non existing site.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Unable to reproduce in current version

**Comment by juacamar** [comment]
Bug closed as won't fix, in last browser version it is not reproduced.
