### ISSUE TITLE
The location map is not displayed on Safari browser.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-artshowcase#23]
Description: 
The location map is not displayed on Safari browser.
 
-Env:
Crafter Exigo Blueprint
Device: MacBook Pro 
Safari Version 8.0.5 (10600.5.17)
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Exigo site.
2. Go to the “Contact us” section.
 
CURRENT RESULT: 
==================== 
The location map is not displayed on Safari browser.
https://www.screencast.com/t/RQwhj3nI5 
 
EXPECTED RESULT: 
==================== 
The location map should be displayed on Safari browser.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build 8380508
