### ISSUE TITLE
The gallery images are not displayed properly in Apple devices.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-artshowcase#24]
Description: 
The gallery images are not displayed properly in Apple devices.
 
Device: Iphone 6 IOS 10.2 Safari	
	     Iphone 7 IOS 10.3 Safari
Google Chrome 55.0.2883.79
 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Exigo site.
2. Go to the “Gallery” section.
 
CURRENT RESULT: 
==================== 
The gallery images are not displayed properly in Apple devices.
https://www.screencast.com/t/nECUymH56d0 
 
EXPECTED RESULT: 
==================== 
The gallery images should be displayed properly in Apple devices.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug still reproduces in build cffd527.

**Comment by juacamar** [comment]
Bug verified and closed as fixed
