### ISSUE TITLE
The gallery images are not displayed properly arranged.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-artshowcase#25]
Description: 
The gallery images are not displayed properly arranged, images should be properly aligned and have similar sizes. 
 
Env.
Crafter Exigo Blueprint
Device: MacBook Pro 
Google Chrome Version 58.0.3029.110 (64-bit)
Firefox 53.0 (64-bit
Safari Version 8.0.5 (10600.5.17)

Device: Android 7.1.1 
Google Chrome 58.0.3029.83

REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Exigo site.
2. Go to the “Gallery” section.
 
CURRENT RESULT: 
==================== 
The gallery images are not displayed properly arranged.
https://www.screencast.com/t/QEnSxBrCNHRJ 
https://www.screencast.com/t/48JiK0YRs 
*Mobile
https://www.screencast.com/t/Bpcfg9qyYfBa 
 
 
EXPECTED RESULT: 
==================== 
The gallery images should be displayed properly arranged.
*Check the template order.
https://www.screencast.com/t/am9EWWhNfkl0

**Comment by LorenzoRodriguezRivetlogic** [comment]
Not a bug

**Comment by juacamar** [comment]
But closed as is not a bug (Gallery works as it was defined) in build 8380508.
