### ISSUE TITLE
The testimonials characters limit should be shorter, so the page is  always displayed properly.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-artshowcase#3]
The testimonials characters limit should be shorter, so the page is  always displayed properly.

-Env:
Using the Exigo Blueprint
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 

Description: The testimonial character limit is 100.000, so when the user writes a larger testimonial the page is not displayed properly.

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Exigo site.
2. On the site bar, locate the components section.
3. Click on the edit button of the Testimonials Carousel.
4. Add a new Testimonial.
Eg. Reviewer: John A.
       Testimonial: Field At least 30.000 characters 
4. Click on the Save and Close Button.
5. Go to the Page preview the testimonial section.

*Video
https://www.screencast.com/t/JhdUEHBp

CURRENT RESULT: 
==================== 
The application displays the testimonial properly but, when the user selects another shorter testimonial the page design is not displayed properly

EXPECTED RESULT: 
==================== 
 The testimonials characters limit should be shorter, so the page is  always displayed properly.

**Comment by efaj** [comment]
assign @juacamar

**Comment by juacamar** [comment]
Bug Verified and closed as Fixed.
