### ISSUE TITLE
The application have an scroll issue when the user scroll into the “Map” section in mobile.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-artshowcase#33]
Description:  
The site have an scroll issue when the user scroll into the “Map” section or go directly to the map section by using the menu in mobile.
 
-Env:
Crafter Art Show Case Blueprint
Device: Iphone 6 plus
Safari IOS 10.3
Safari
Google Chrome Version 55.0.2883.79
Android 7.1
Google Chrome 55.0.2883.79
Firefox 54.0
 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Art Showcase site.
2. Scroll to the end of the site.(check when scroll get to the map section)
3. Reload the page.
4.In the menu select the “Contact Us” option.
5. Scroll to the end of the site
 
CURRENT RESULT: 
==================== 
The application have an scroll issue when the user scroll into the “Map” section  in mobile.
https://www.screencast.com/t/agfIZENb 
 
EXPECTED RESULT: 
==================== 
The application should not have an scroll issue when the user scroll into the “Map” section  in mobile.

**Comment by efaj** [comment]
Issue was replicated even in Google's samples. It happens with the "cooperative" gestureHandling, which is a relatively recent feature... I was unable to find any more information or any fix by googling.
Since it seems like a bug on Google's side, it's likely it'll get fixed soon-ish, but I was unable to find any bug report to subscribe to.

**Comment by efaj** [comment]
@juacamar

**Comment by juacamar** [comment]
Bug verified and closed as fixed (Disable gesture controls as cooperative mode was causing scrolling).
