### ISSUE TITLE
The map is not displayed when the location values are invalid.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-artshowcase#4]
Description: When the location latitude and longitude are invalid, the map is not displayed.

-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1.Open the Crafter studio with the Exigo site.
2. On the site bar, click on the edit button of the home page.
3. Go to the Footer Section and field the Latitude and Longitude values with an invalid location.
 eg. Latitude: 20.00
       Longitude: 20.00
4. Click on the Save and Close Button.
5. Go to the Page preview and check the map.

CURRENT RESULT: 
==================== 
The application should allow the user to save changes when the location values are not valid, this causes that the map is not displayed.
https://www.screencast.com/t/tTPDCw3Z5 

EXPECTED RESULT: 
==================== 
The application should not allow the user to save the changes when the location values are not valid, so the map is always displayed with a valid location.

**Comment by efaj** [comment]
Add a hint

**Comment by juacamar** [comment]
Bug verified and closed as fixed.
