### ISSUE TITLE
The Photo, “Full Name” and “Title” fields should be required fields in the Curator's section.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-artshowcase#5]
Description: The application allows the user to create a new curator without fill out the Photo, “Full Name” and “Title” fields that are required fields.

-Env:
Crafter Exigo Blueprint
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Exigo site.
2. On the site bar, locate the components section.
3. Click on the edit button of the Curators list.
4. Click on the “Add Another” Button.
5. Fill out only the Facebook and Google Plus URL.
4. Click on the Save and Close Button.
5. Go to the Page preview the Curators section.

CURRENT RESULT: 
==================== 
The application displays the Curator with a blank photo and the Facebook and Google Plus links.
https://screencast.com/t/2WotIWtuWlEr 

EXPECTED RESULT: 
==================== 
The application should not allow the user to save changes until all the required values of the curator are fulfilled.

**Comment by efaj** [comment]
Fixed in 34f84e00faef331576c492e84ed34e3bfe3167fd

**Comment by juacamar** [comment]
Bug verified and closed as fixed.

**Comment by juacamar** [comment]
Bug verified and closed as fixed.
