### ISSUE TITLE
The “Intro Section” should limit the amount and the type of components to be added.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-artshowcase#8]
Description: 
The “Intro Section” should limit the amount and the type of components to be added.

-Env:
Crafter Exigo Blueprint
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 

REPRODUCIBILITY LEVEL: 
==================== 
Always 

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Exigo site.
2. On the site bar, locate the Sections.
3. Click on the edit button of the “Intro Section”.
4. Click on the “Add” button
5. Select the “Browse for existing -Components”
6. Select “Intro Hero Text” component
7. Click on the “Add” button
8. Select the “Browse for existing -Components”
9. Select “Curators” component
10. Click on the “Save and Close” button.
11. Review the Intro Section

CURRENT RESULT: 
==================== 
The application allows to add as many components as user wants. Also the application allows the user to add any type of component.
https://www.screencast.com/t/A0WtFhRHnk

EXPECTED RESULT: 
==================== 
The application should limit the amount components to be added. Also the application should only allows the user to add the proper type of component.

**Comment by efaj** [comment]
@juacamar

**Comment by efaj** [comment]
assign @juacamar
